services:
  Saloodo\MailBundle\EmailSender:
    public: true
    arguments:
        - '@Saloodo\MailBundle\Adapters\LoggerAdapter'
  Saloodo\MailBundle\Adapters\SalesForceAdapter:
    arguments:
        - ''
        - ''
        - ''
        - ''
        - '@event_dispatcher'

  Saloodo\MailBundle\Adapters\LoggerAdapter:
      arguments:
          - '@logger'
